### ISSUE TITLE
Staticman Netlify Function on Gitlab

### ISSUE THREAD

**Issue by ZDVokoun** [eduardoboucas/eleventy-blog-staticman#1]
I'm trying to run this template on Gitlab, but when I enter `GITLAB_TOKEN` instead of `GITHUB_TOKEN`, I get this error:
```
{"errorType":"Error","errorMessage":"Require an `oauthToken` or `token` option","trace":["Error: Require an `oauthToken` or `token` option","    at /var/task/src/node_modules/@staticman/core/build/lib/GitHub.js:47:15","    at new GitHub (/var/task/src/node_modules/@staticman/core/build/lib/GitHub.js:59:7)","    at _default (/var/task/src/node_modules/@staticman/core/build/lib/GitServiceFactory.js:20:14)","    at /var/task/src/node_modules/@staticman/core/build/lib/Staticman.js:65:55","    at new Staticman (/var/task/src/node_modules/@staticman/core/build/lib/Staticman.js:85:7)","    at processEntry (/var/task/src/node_modules/@staticman/netlify-functions/build/processEntry.js:101:27)","    at Runtime.exports.handler (/var/task/src/functions/staticman.js:41:10)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
```
Does this template support Gitlab?

**Comment by josineto** [comment]
Hi @ZDVokoun , did you find a solution? I have exact same problem. Digging into code from [@staticman/netlify-functions](https://www.npmjs.com/package/@staticman/netlify-functions) (`build` folder), it seems that package uses Staticman `v2` api:

In a normal Staticman `v3`, the instance path is decomposed into `:service/:user/:repository`. `:service` is, in our case, `gitlab`, which internally routes Staticman into processing via GitLab. But the NPM package used in this repository (@staticman/netlify-functions) doesn't recognize that `:service` part, only `:user/:repository`. Since `service` is not read, Staticman assumes default route, which is GitHub processing...

@eduardoboucas please, are there any plans on either fixing this, or submitting @staticman/netlify-functions to an autonomous Git repository, where it could be worked by others?

**Comment by ZDVokoun** [comment]
Hi @jzeneto, you can get it working with [bashlk/staticman-netlify-function](https://github.com/bashlk/staticman-netlify-function/) when you add `service: gitlab` in [here](https://github.com/bashlk/staticman-netlify-function/blob/master/functions/staticman/staticman.js#L11). I know that the solution isn't perfect, but it worked for me.

**Comment by josineto** [comment]
@ZDVokoun **thank you**! It works! Thank you, really!
